[project]
name = "discworld_cli"
version = "1.0.0"
requires-python = ">=3.10"
dependencies = ["typer>=0.12", "rich>=13", "black (>=25.1.0,<26.0.0)", "flake8 (>=7.3.0,<8.0.0)"]

[project.scripts]
discworld-cli = "discworld_cli.cli.app:main"
